
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop-second?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

#图片上传
web:
  upload path: D:/images/ #图片上传的路径
  load-path: file:D://images/ #图片访问、加载的路径


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_empty

logging:
  pattern:
      console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'

server:
  port: 8089



